-- ===========================================================================
-- ESQUEMA COMPLETO
-- ===========================================================================
--
-- Todas las tablas, en un solo archivo. Los datos van en V002.
--
-- Por qué dos archivos y no una migración por cambio: este repositorio nunca
-- ha estado desplegado. Mientras no haya una base en producción que proteger,
-- un historial de ocho migraciones es un historial de decisiones internas que
-- nadie va a volver a leer, y obliga a reconstruir mentalmente el esquema
-- saltando entre archivos para saber qué columnas tiene una tabla. Aquí se lee
-- de arriba abajo.
--
-- **El día que esto se despliegue, esta consolidación se acabó**: a partir de
-- ahí cada cambio es una migración nueva (V003, V004…) y estos dos archivos no
-- se tocan nunca más. Flyway calcula el checksum del archivo completo.
--
-- Convención de nombres (ADR-0011):
--   tabla            español, singular            producto
--   clave primaria   id_<tabla>                   producto.id_producto
--   clave foránea    fk_id_<tabla_referenciada>   producto.fk_id_subcategoria
--   restricciones    pk_ uq_ fk_ ck_ ix_ + tabla
--
-- Bloque de auditoría, idéntico en toda tabla de negocio:
--   creado_en, creado_por, actualizado_en, actualizado_por, version
--
-- Eliminación lógica (RN-086), donde aplica:
--   eliminado_en, eliminado_por  — las dos o ninguna, lo exige un CHECK

-- Búsqueda por nombre con ILIKE: sin trigramas es siempre un recorrido
-- completo de tabla. Ver ix_producto_busqueda.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ===========================================================================
-- 1. Archivos
-- ===========================================================================

-- Un archivo es inmutable (RN-075): no se edita, se reemplaza. Por eso no
-- lleva actualizado_por ni version: nada lo actualiza nunca. Y queda fuera de
-- la eliminación lógica: solo se borra cuando ya no lo referencia nadie, así
-- que no hay nada que conservar ni a quién explicárselo.
CREATE TABLE archivo (
    id_archivo      bigint GENERATED BY DEFAULT AS IDENTITY,
    clave           varchar(300) NOT NULL,
    nombre_original varchar(255) NOT NULL,
    tipo_mime       varchar(60)  NOT NULL,
    bytes           bigint       NOT NULL,
    ancho           integer      NOT NULL,
    alto            integer      NOT NULL,
    texto_alt       varchar(200) NOT NULL,
    hash_contenido  varchar(64)  NOT NULL,
    url_publica     varchar(500) NOT NULL,
    creado_en       timestamptz  NOT NULL DEFAULT now(),
    creado_por      varchar(60)  NOT NULL DEFAULT 'sistema',
    CONSTRAINT pk_archivo           PRIMARY KEY (id_archivo),
    CONSTRAINT uq_archivo_clave     UNIQUE (clave),
    CONSTRAINT ck_archivo_tipo_mime CHECK (tipo_mime = 'image/webp'),
    CONSTRAINT ck_archivo_bytes     CHECK (bytes > 0),
    CONSTRAINT ck_archivo_dimension CHECK (ancho > 0 AND alto > 0)
);

-- La misma imagen en varios tamaños. El original acotado también es una
-- variante: así la consulta que arma una etiqueta picture es una sola.
CREATE TABLE archivo_variante (
    id_archivo_variante bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_archivo       bigint       NOT NULL,
    nombre              varchar(20)  NOT NULL,
    clave               varchar(300) NOT NULL,
    url_publica         varchar(500) NOT NULL,
    ancho               integer      NOT NULL,
    alto                integer      NOT NULL,
    bytes               bigint       NOT NULL,
    CONSTRAINT pk_archivo_variante         PRIMARY KEY (id_archivo_variante),
    CONSTRAINT fk_archivo_variante_archivo FOREIGN KEY (fk_id_archivo)
        REFERENCES archivo (id_archivo) ON DELETE CASCADE,
    CONSTRAINT uq_archivo_variante_nombre  UNIQUE (fk_id_archivo, nombre),
    CONSTRAINT ck_archivo_variante_nombre  CHECK (nombre IN ('MINIATURA', 'TARJETA', 'DETALLE', 'ORIGINAL'))
);

-- ===========================================================================
-- 2. Ubigeo del Perú
-- ===========================================================================
--
-- Catálogo nacional: lo administra la plataforma, no se edita desde el panel.
-- Por eso no lleva auditoría ni eliminación lógica — no hay «quién lo cambió»
-- porque nadie lo cambia.
--
-- Tres tablas y no una con tres columnas de texto: una dirección tiene que
-- apuntar a un distrito real, y «Lima / Lima / Miraflores» escrito a mano
-- tiene tantas grafías como quien la teclee.

CREATE TABLE departamento (
    id_departamento smallint GENERATED BY DEFAULT AS IDENTITY,
    nombre          varchar(60) NOT NULL,
    CONSTRAINT pk_departamento        PRIMARY KEY (id_departamento),
    CONSTRAINT uq_departamento_nombre UNIQUE (nombre)
);

CREATE TABLE provincia (
    id_provincia       smallint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_departamento smallint    NOT NULL,
    nombre             varchar(60) NOT NULL,
    CONSTRAINT pk_provincia             PRIMARY KEY (id_provincia),
    CONSTRAINT fk_provincia_departamento FOREIGN KEY (fk_id_departamento)
        REFERENCES departamento (id_departamento),
    -- Único dentro del departamento, no en todo el país: hay una provincia
    -- «Lima» y un departamento «Lima», y varias provincias homónimas.
    CONSTRAINT uq_provincia_nombre      UNIQUE (fk_id_departamento, nombre)
);

CREATE INDEX ix_provincia_departamento ON provincia (fk_id_departamento, nombre);

CREATE TABLE distrito (
    id_distrito     integer GENERATED BY DEFAULT AS IDENTITY,
    fk_id_provincia smallint    NOT NULL,
    nombre          varchar(60) NOT NULL,
    CONSTRAINT pk_distrito           PRIMARY KEY (id_distrito),
    CONSTRAINT fk_distrito_provincia FOREIGN KEY (fk_id_provincia) REFERENCES provincia (id_provincia),
    CONSTRAINT uq_distrito_nombre    UNIQUE (fk_id_provincia, nombre)
);

CREATE INDEX ix_distrito_provincia ON distrito (fk_id_provincia, nombre);

-- ===========================================================================
-- 3. Clientes
-- ===========================================================================
--
-- Tabla separada de la de administradores (ADR-0008). Con una sola tabla y un
-- campo `rol`, cualquier fallo del registro público sería una escalada a
-- administrador; aquí ese camino no existe.

CREATE TABLE cliente (
    id_cliente       bigint GENERATED BY DEFAULT AS IDENTITY,
    email            varchar(160) NOT NULL,
    email_verificado boolean      NOT NULL DEFAULT false,
    -- Nulo es un estado legítimo: quien entró con Google no tiene contraseña,
    -- y pedirle «la actual» para cambiarla no tendría sentido.
    hash_contrasena  varchar(120),
    nombre           varchar(120) NOT NULL,
    telefono         varchar(20),
    activo           boolean      NOT NULL DEFAULT true,
    ultimo_acceso_en timestamptz,
    creado_en        timestamptz  NOT NULL DEFAULT now(),
    creado_por       varchar(60)  NOT NULL DEFAULT 'sistema',
    actualizado_en   timestamptz  NOT NULL DEFAULT now(),
    actualizado_por  varchar(60)  NOT NULL DEFAULT 'sistema',
    version          integer      NOT NULL DEFAULT 0,
    eliminado_en     timestamptz,
    eliminado_por    varchar(60),
    CONSTRAINT pk_cliente           PRIMARY KEY (id_cliente),
    CONSTRAINT ck_cliente_eliminado CHECK ((eliminado_en IS NULL) = (eliminado_por IS NULL)),
    -- El correo en minúsculas es la identidad. Se comprueba con lower() para
    -- que Ana@x.com y ana@x.com no sean dos cuentas distintas.
    CONSTRAINT ck_cliente_email     CHECK (email = lower(email))
);

CREATE UNIQUE INDEX uq_cliente_email ON cliente (email) WHERE eliminado_en IS NULL;
CREATE INDEX ix_cliente_nombre ON cliente (nombre);

-- Acceso con Google.
--
-- Tabla aparte y no dos columnas en `cliente` porque una cuenta puede tener
-- varias identidades —hoy Google, mañana otra— y porque el identificador que
-- importa es el `subject` del proveedor, no el correo: Google permite cambiar
-- el correo de una cuenta sin que deje de ser la misma persona.
CREATE TABLE identidad_externa (
    id_identidad_externa bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_cliente        bigint       NOT NULL,
    proveedor            varchar(20)  NOT NULL,
    -- El `sub` del token de Google. Estable e irrepetible para siempre.
    sujeto               varchar(255) NOT NULL,
    email                varchar(160) NOT NULL,
    nombre               varchar(160),
    url_foto             varchar(500),
    creado_en            timestamptz  NOT NULL DEFAULT now(),
    ultimo_acceso_en     timestamptz,
    CONSTRAINT pk_identidad_externa         PRIMARY KEY (id_identidad_externa),
    CONSTRAINT fk_identidad_externa_cliente FOREIGN KEY (fk_id_cliente)
        REFERENCES cliente (id_cliente) ON DELETE CASCADE,
    CONSTRAINT uq_identidad_externa_sujeto  UNIQUE (proveedor, sujeto),
    -- Una cuenta no puede tener dos identidades del mismo proveedor: sería
    -- ambiguo al iniciar sesión.
    CONSTRAINT uq_identidad_externa_cliente UNIQUE (fk_id_cliente, proveedor),
    CONSTRAINT ck_identidad_externa_prov    CHECK (proveedor IN ('GOOGLE'))
);

-- Token de refresco de la tienda. Mismo diseño que el del panel: se guarda el
-- hash, y la familia agrupa la cadena de rotaciones de un mismo acceso.
CREATE TABLE token_refresco_cliente (
    id_token_refresco_cliente bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_cliente             bigint      NOT NULL,
    hash_token                varchar(64) NOT NULL,
    familia                   uuid        NOT NULL,
    expira_en                 timestamptz NOT NULL,
    usado_en                  timestamptz,
    revocado_en               timestamptz,
    creado_en                 timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_token_refresco_cliente      PRIMARY KEY (id_token_refresco_cliente),
    CONSTRAINT uq_token_refresco_cliente_hash UNIQUE (hash_token),
    CONSTRAINT fk_token_refresco_cliente_cliente FOREIGN KEY (fk_id_cliente)
        REFERENCES cliente (id_cliente) ON DELETE CASCADE
);

CREATE INDEX ix_token_refresco_cliente_familia ON token_refresco_cliente (familia);
CREATE INDEX ix_token_refresco_cliente_expira  ON token_refresco_cliente (expira_en);

-- Correo de verificación y recuperación de contraseña: un solo uso, caduca.
CREATE TABLE token_cliente (
    id_token_cliente bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_cliente    bigint      NOT NULL,
    tipo             varchar(20) NOT NULL,
    hash_token       varchar(64) NOT NULL,
    expira_en        timestamptz NOT NULL,
    usado_en         timestamptz,
    creado_en        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_token_cliente         PRIMARY KEY (id_token_cliente),
    CONSTRAINT uq_token_cliente_hash    UNIQUE (hash_token),
    CONSTRAINT fk_token_cliente_cliente FOREIGN KEY (fk_id_cliente)
        REFERENCES cliente (id_cliente) ON DELETE CASCADE,
    CONSTRAINT ck_token_cliente_tipo    CHECK (tipo IN ('VERIFICAR_EMAIL', 'RECUPERAR_CONTRASENA'))
);

CREATE INDEX ix_token_cliente_expira ON token_cliente (expira_en);

-- ---------------------------------------------------------------------------
-- Direcciones
-- ---------------------------------------------------------------------------
--
-- El distrito es obligatorio y referenciado; la latitud y la longitud son
-- opcionales porque salen de marcar un punto en el mapa, y no todo el mundo lo
-- hará. Cuando están, son lo que de verdad encuentra el repartidor: «Av. Los
-- Olivos 123» tiene decenas de homónimos en Lima, un par de coordenadas no.
CREATE TABLE direccion_cliente (
    id_direccion_cliente bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_cliente        bigint        NOT NULL,
    fk_id_distrito       integer       NOT NULL,
    -- «Casa», «Oficina». Para que el cliente distinga las suyas de un vistazo.
    etiqueta             varchar(40)   NOT NULL,
    destinatario         varchar(120)  NOT NULL,
    telefono             varchar(20)   NOT NULL,
    calle                varchar(200)  NOT NULL,
    numero               varchar(20),
    -- Interior, piso, manzana y lote: lo que no cabe en «calle y número».
    referencia           varchar(300),
    codigo_postal        varchar(12),
    latitud              numeric(10,7),
    longitud             numeric(10,7),
    predeterminada       boolean       NOT NULL DEFAULT false,
    creado_en            timestamptz   NOT NULL DEFAULT now(),
    creado_por           varchar(60)   NOT NULL DEFAULT 'sistema',
    actualizado_en       timestamptz   NOT NULL DEFAULT now(),
    actualizado_por      varchar(60)   NOT NULL DEFAULT 'sistema',
    version              integer       NOT NULL DEFAULT 0,
    eliminado_en         timestamptz,
    eliminado_por        varchar(60),
    CONSTRAINT pk_direccion_cliente          PRIMARY KEY (id_direccion_cliente),
    CONSTRAINT fk_direccion_cliente_cliente  FOREIGN KEY (fk_id_cliente)
        REFERENCES cliente (id_cliente) ON DELETE CASCADE,
    CONSTRAINT fk_direccion_cliente_distrito FOREIGN KEY (fk_id_distrito) REFERENCES distrito (id_distrito),
    CONSTRAINT ck_direccion_cliente_elim     CHECK ((eliminado_en IS NULL) = (eliminado_por IS NULL)),
    -- O las dos coordenadas o ninguna: media coordenada no ubica nada.
    CONSTRAINT ck_direccion_cliente_punto    CHECK ((latitud IS NULL) = (longitud IS NULL)),
    CONSTRAINT ck_direccion_cliente_latitud  CHECK (latitud  IS NULL OR latitud  BETWEEN -90  AND 90),
    CONSTRAINT ck_direccion_cliente_longitud CHECK (longitud IS NULL OR longitud BETWEEN -180 AND 180)
);

CREATE INDEX ix_direccion_cliente_cliente ON direccion_cliente (fk_id_cliente)
    WHERE eliminado_en IS NULL;

-- Una sola dirección predeterminada por cliente, garantizado por la base y no
-- por el servicio: dos peticiones simultáneas ganan la carrera las dos.
CREATE UNIQUE INDEX uq_direccion_cliente_predeterminada ON direccion_cliente (fk_id_cliente)
    WHERE predeterminada AND eliminado_en IS NULL;

-- ===========================================================================
-- 4. Catálogo
-- ===========================================================================

CREATE TABLE marca (
    id_marca        bigint GENERATED BY DEFAULT AS IDENTITY,
    nombre          varchar(80)  NOT NULL,
    slug            varchar(100) NOT NULL,
    descripcion     varchar(500),
    fk_id_archivo   bigint,
    activa          boolean      NOT NULL DEFAULT true,
    creado_en       timestamptz  NOT NULL DEFAULT now(),
    creado_por      varchar(60)  NOT NULL DEFAULT 'sistema',
    actualizado_en  timestamptz  NOT NULL DEFAULT now(),
    actualizado_por varchar(60)  NOT NULL DEFAULT 'sistema',
    version         integer      NOT NULL DEFAULT 0,
    eliminado_en    timestamptz,
    eliminado_por   varchar(60),
    CONSTRAINT pk_marca         PRIMARY KEY (id_marca),
    CONSTRAINT fk_marca_archivo FOREIGN KEY (fk_id_archivo) REFERENCES archivo (id_archivo),
    CONSTRAINT ck_marca_eliminado CHECK ((eliminado_en IS NULL) = (eliminado_por IS NULL))
);

-- Una categoría NO contiene productos: solo subcategorías (modelo-dominio.md).
CREATE TABLE categoria (
    id_categoria    bigint GENERATED BY DEFAULT AS IDENTITY,
    nombre          varchar(80)  NOT NULL,
    slug            varchar(100) NOT NULL,
    descripcion     varchar(500),
    fk_id_archivo   bigint,
    orden           integer      NOT NULL DEFAULT 0,
    activa          boolean      NOT NULL DEFAULT true,
    creado_en       timestamptz  NOT NULL DEFAULT now(),
    creado_por      varchar(60)  NOT NULL DEFAULT 'sistema',
    actualizado_en  timestamptz  NOT NULL DEFAULT now(),
    actualizado_por varchar(60)  NOT NULL DEFAULT 'sistema',
    version         integer      NOT NULL DEFAULT 0,
    eliminado_en    timestamptz,
    eliminado_por   varchar(60),
    CONSTRAINT pk_categoria         PRIMARY KEY (id_categoria),
    CONSTRAINT fk_categoria_archivo FOREIGN KEY (fk_id_archivo) REFERENCES archivo (id_archivo),
    CONSTRAINT ck_categoria_eliminado CHECK ((eliminado_en IS NULL) = (eliminado_por IS NULL))
);

-- El nombre es único DENTRO de la categoría (Accesorios existe bajo
-- Tecnología y bajo Deportes); el slug es único globalmente, para que
-- /c/accesorios-tecnologia no necesite saber el padre.
CREATE TABLE subcategoria (
    id_subcategoria  bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_categoria  bigint       NOT NULL,
    nombre           varchar(80)  NOT NULL,
    slug             varchar(120) NOT NULL,
    descripcion      varchar(500),
    fk_id_archivo    bigint,
    orden            integer      NOT NULL DEFAULT 0,
    activa           boolean      NOT NULL DEFAULT true,
    creado_en        timestamptz  NOT NULL DEFAULT now(),
    creado_por       varchar(60)  NOT NULL DEFAULT 'sistema',
    actualizado_en   timestamptz  NOT NULL DEFAULT now(),
    actualizado_por  varchar(60)  NOT NULL DEFAULT 'sistema',
    version          integer      NOT NULL DEFAULT 0,
    eliminado_en     timestamptz,
    eliminado_por    varchar(60),
    CONSTRAINT pk_subcategoria           PRIMARY KEY (id_subcategoria),
    CONSTRAINT fk_subcategoria_categoria FOREIGN KEY (fk_id_categoria) REFERENCES categoria (id_categoria),
    CONSTRAINT fk_subcategoria_archivo   FOREIGN KEY (fk_id_archivo)   REFERENCES archivo (id_archivo),
    CONSTRAINT ck_subcategoria_eliminado CHECK ((eliminado_en IS NULL) = (eliminado_por IS NULL))
);

CREATE INDEX ix_subcategoria_categoria ON subcategoria (fk_id_categoria, orden, nombre);

CREATE TABLE producto (
    id_producto           bigint GENERATED BY DEFAULT AS IDENTITY,
    sku                   varchar(40)   NOT NULL,
    nombre                varchar(160)  NOT NULL,
    slug                  varchar(200)  NOT NULL,
    descripcion_corta     varchar(300),
    descripcion           text,
    fk_id_subcategoria    bigint        NOT NULL,
    fk_id_marca           bigint,
    precio                numeric(12,2) NOT NULL,
    precio_anterior       numeric(12,2),
    stock                 integer       NOT NULL DEFAULT 0,
    destacado             boolean       NOT NULL DEFAULT false,
    activo                boolean       NOT NULL DEFAULT false,
    calificacion_promedio numeric(2,1)  NOT NULL DEFAULT 0,
    calificacion_conteo   integer       NOT NULL DEFAULT 0,
    -- Contador simple, no una tabla de eventos (RN-085). Para «qué producto se
    -- mira más» basta, y una fila por visita a un catálogo público crece sin
    -- límite.
    vistas                bigint        NOT NULL DEFAULT 0,
    creado_en             timestamptz   NOT NULL DEFAULT now(),
    creado_por            varchar(60)   NOT NULL DEFAULT 'sistema',
    actualizado_en        timestamptz   NOT NULL DEFAULT now(),
    actualizado_por       varchar(60)   NOT NULL DEFAULT 'sistema',
    version               integer       NOT NULL DEFAULT 0,
    eliminado_en          timestamptz,
    eliminado_por         varchar(60),
    CONSTRAINT pk_producto                 PRIMARY KEY (id_producto),
    -- El SKU NO se libera al eliminar: aparece copiado en las líneas de orden,
    -- y reutilizarlo haría que dos productos distintos compartan identificador
    -- en un histórico que ya no se puede cambiar.
    CONSTRAINT uq_producto_sku             UNIQUE (sku),
    CONSTRAINT fk_producto_subcategoria    FOREIGN KEY (fk_id_subcategoria) REFERENCES subcategoria (id_subcategoria),
    CONSTRAINT fk_producto_marca           FOREIGN KEY (fk_id_marca)        REFERENCES marca (id_marca),
    -- RN-003: el precio es estrictamente positivo. Un producto a cero no es
    -- gratis, es un error de captura.
    CONSTRAINT ck_producto_precio          CHECK (precio > 0),
    -- RN-004 / I-7: un descuento que sube el precio es un error de captura.
    CONSTRAINT ck_producto_precio_anterior CHECK (precio_anterior IS NULL OR precio_anterior > precio),
    CONSTRAINT ck_producto_stock           CHECK (stock >= 0),
    CONSTRAINT ck_producto_calificacion    CHECK (calificacion_promedio BETWEEN 0 AND 5),
    CONSTRAINT ck_producto_eliminado       CHECK ((eliminado_en IS NULL) = (eliminado_por IS NULL))
);

CREATE INDEX ix_producto_subcategoria     ON producto (fk_id_subcategoria);
CREATE INDEX ix_producto_marca            ON producto (fk_id_marca);
CREATE INDEX ix_producto_activo_destacado ON producto (activo, destacado);
CREATE INDEX ix_producto_precio           ON producto (precio);
CREATE INDEX ix_producto_creado_en        ON producto (creado_en DESC);
CREATE INDEX ix_producto_vistas           ON producto (vistas DESC);

-- RN-021: búsqueda por nombre y descripción corta. El trigrama es lo que
-- permite que un LIKE con comodín por delante use índice.
CREATE INDEX ix_producto_busqueda ON producto
    USING gin ((nombre || ' ' || coalesce(descripcion_corta, '')) gin_trgm_ops);

-- Orden explícito: la primera imagen es la principal. Sin UNIQUE sobre
-- (producto, orden) a propósito: reordenar exigiría restricciones diferidas
-- para no chocar a mitad del intercambio.
CREATE TABLE producto_imagen (
    id_producto_imagen bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_producto     bigint  NOT NULL,
    fk_id_archivo      bigint  NOT NULL,
    orden              integer NOT NULL DEFAULT 0,
    CONSTRAINT pk_producto_imagen          PRIMARY KEY (id_producto_imagen),
    CONSTRAINT fk_producto_imagen_producto FOREIGN KEY (fk_id_producto) REFERENCES producto (id_producto) ON DELETE CASCADE,
    CONSTRAINT fk_producto_imagen_archivo  FOREIGN KEY (fk_id_archivo)  REFERENCES archivo (id_archivo),
    CONSTRAINT uq_producto_imagen          UNIQUE (fk_id_producto, fk_id_archivo)
);

CREATE INDEX ix_producto_imagen_producto ON producto_imagen (fk_id_producto, orden);

-- ---------------------------------------------------------------------------
-- Unicidad del catálogo: qué se libera al eliminar y qué no (RN-086)
-- ---------------------------------------------------------------------------
--
-- Los nombres y los slugs SÍ se liberan. Si alguien elimina la marca «Pulse»
-- por error y la vuelve a crear, exigirle «Pulse 2» porque queda una fila
-- invisible es castigarle por un borrado que ya se deshizo.
--
-- El SKU, el código de cupón y el usuario NO (van como UNIQUE de tabla, arriba).

CREATE UNIQUE INDEX uq_marca_nombre        ON marca (nombre)                       WHERE eliminado_en IS NULL;
CREATE UNIQUE INDEX uq_marca_slug          ON marca (slug)                         WHERE eliminado_en IS NULL;
CREATE UNIQUE INDEX uq_categoria_nombre    ON categoria (nombre)                   WHERE eliminado_en IS NULL;
CREATE UNIQUE INDEX uq_categoria_slug      ON categoria (slug)                     WHERE eliminado_en IS NULL;
CREATE UNIQUE INDEX uq_subcategoria_nombre ON subcategoria (fk_id_categoria, nombre) WHERE eliminado_en IS NULL;
CREATE UNIQUE INDEX uq_subcategoria_slug   ON subcategoria (slug)                  WHERE eliminado_en IS NULL;
CREATE UNIQUE INDEX uq_producto_slug       ON producto (slug)                      WHERE eliminado_en IS NULL;

-- Índices para la papelera: sin ellos, listar lo eliminado recorre la tabla
-- entera, y lo eliminado es siempre una fracción mínima de las filas.
CREATE INDEX ix_marca_eliminado        ON marca (eliminado_en)        WHERE eliminado_en IS NOT NULL;
CREATE INDEX ix_categoria_eliminado    ON categoria (eliminado_en)    WHERE eliminado_en IS NOT NULL;
CREATE INDEX ix_subcategoria_eliminado ON subcategoria (eliminado_en) WHERE eliminado_en IS NOT NULL;
CREATE INDEX ix_producto_eliminado     ON producto (eliminado_en)     WHERE eliminado_en IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Favoritos
-- ---------------------------------------------------------------------------
--
-- Del cliente y no del navegador: la gracia de una lista de deseos es que
-- sobreviva al cambio de dispositivo. Sin auditoría —solo importa cuándo se
-- añadió— y con borrado físico: quitar algo de favoritos no es un hecho que
-- haya que conservar.
CREATE TABLE favorito (
    id_favorito    bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_cliente  bigint      NOT NULL,
    fk_id_producto bigint      NOT NULL,
    creado_en      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_favorito          PRIMARY KEY (id_favorito),
    CONSTRAINT fk_favorito_cliente  FOREIGN KEY (fk_id_cliente)  REFERENCES cliente (id_cliente) ON DELETE CASCADE,
    CONSTRAINT fk_favorito_producto FOREIGN KEY (fk_id_producto) REFERENCES producto (id_producto) ON DELETE CASCADE,
    -- Pulsar dos veces el corazón no crea dos favoritos.
    CONSTRAINT uq_favorito          UNIQUE (fk_id_cliente, fk_id_producto)
);

CREATE INDEX ix_favorito_cliente ON favorito (fk_id_cliente, creado_en DESC);

-- ===========================================================================
-- 5. Carrito y cupones
-- ===========================================================================

CREATE TABLE cupon (
    id_cupon        bigint GENERATED BY DEFAULT AS IDENTITY,
    codigo          varchar(40)   NOT NULL,
    tipo            varchar(12)   NOT NULL,
    valor           numeric(12,2) NOT NULL,
    subtotal_minimo numeric(12,2) NOT NULL DEFAULT 0,
    inicia_en       timestamptz   NOT NULL,
    termina_en      timestamptz   NOT NULL,
    usos_maximos    integer,
    usos_actuales   integer       NOT NULL DEFAULT 0,
    activo          boolean       NOT NULL DEFAULT true,
    creado_en       timestamptz   NOT NULL DEFAULT now(),
    creado_por      varchar(60)   NOT NULL DEFAULT 'sistema',
    actualizado_en  timestamptz   NOT NULL DEFAULT now(),
    actualizado_por varchar(60)   NOT NULL DEFAULT 'sistema',
    version         integer       NOT NULL DEFAULT 0,
    eliminado_en    timestamptz,
    eliminado_por   varchar(60),
    CONSTRAINT pk_cupon         PRIMARY KEY (id_cupon),
    -- El código NO se libera al eliminar: queda copiado en las órdenes que lo
    -- usaron.
    CONSTRAINT uq_cupon_codigo  UNIQUE (codigo),
    CONSTRAINT ck_cupon_tipo    CHECK (tipo IN ('PORCENTAJE', 'MONTO_FIJO')),
    CONSTRAINT ck_cupon_valor   CHECK (valor > 0),
    -- Un porcentaje mayor a 100 regalaría dinero; el CHECK lo impide aunque
    -- el servicio falle.
    CONSTRAINT ck_cupon_porcentaje CHECK (tipo <> 'PORCENTAJE' OR valor <= 100),
    CONSTRAINT ck_cupon_periodo CHECK (termina_en > inicia_en),
    CONSTRAINT ck_cupon_usos    CHECK (usos_maximos IS NULL OR usos_actuales <= usos_maximos),
    CONSTRAINT ck_cupon_minimo  CHECK (subtotal_minimo >= 0),
    CONSTRAINT ck_cupon_eliminado CHECK ((eliminado_en IS NULL) = (eliminado_por IS NULL))
);

CREATE INDEX ix_cupon_eliminado ON cupon (eliminado_en) WHERE eliminado_en IS NOT NULL;

-- El id es un UUID porque lo conoce el navegador: un entero secuencial
-- permitiría recorrer los carritos ajenos contando desde 1.
--
-- Queda fuera de la eliminación lógica: un carrito es un estado transitorio,
-- no un hecho que haya que poder explicar meses después.
CREATE TABLE carrito (
    id_carrito      uuid         NOT NULL DEFAULT gen_random_uuid(),
    fk_id_cupon     bigint,
    -- El enlace para fusionar el carrito anónimo al iniciar sesión (RN-036).
    fk_id_cliente   bigint,
    estado          varchar(12)  NOT NULL DEFAULT 'ACTIVO',
    creado_en       timestamptz  NOT NULL DEFAULT now(),
    creado_por      varchar(60)  NOT NULL DEFAULT 'sistema',
    actualizado_en  timestamptz  NOT NULL DEFAULT now(),
    actualizado_por varchar(60)  NOT NULL DEFAULT 'sistema',
    version         integer      NOT NULL DEFAULT 0,
    CONSTRAINT pk_carrito         PRIMARY KEY (id_carrito),
    CONSTRAINT fk_carrito_cupon   FOREIGN KEY (fk_id_cupon)   REFERENCES cupon (id_cupon),
    CONSTRAINT fk_carrito_cliente FOREIGN KEY (fk_id_cliente) REFERENCES cliente (id_cliente),
    CONSTRAINT ck_carrito_estado  CHECK (estado IN ('ACTIVO', 'CONVERTIDO'))
);

CREATE INDEX ix_carrito_cliente ON carrito (fk_id_cliente) WHERE fk_id_cliente IS NOT NULL;

-- RN-031 / I-8: un producto ocupa una sola línea. Lo garantiza uq_item_carrito,
-- no el servicio: dos peticiones simultáneas ganan la carrera las dos.
CREATE TABLE item_carrito (
    id_item_carrito bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_carrito   uuid    NOT NULL,
    fk_id_producto  bigint  NOT NULL,
    cantidad        integer NOT NULL,
    CONSTRAINT pk_item_carrito          PRIMARY KEY (id_item_carrito),
    CONSTRAINT fk_item_carrito_carrito  FOREIGN KEY (fk_id_carrito)  REFERENCES carrito (id_carrito) ON DELETE CASCADE,
    CONSTRAINT fk_item_carrito_producto FOREIGN KEY (fk_id_producto) REFERENCES producto (id_producto),
    CONSTRAINT uq_item_carrito          UNIQUE (fk_id_carrito, fk_id_producto),
    -- RN-034: entre 1 y 99. Cero no es una cantidad, es un DELETE.
    CONSTRAINT ck_item_carrito_cantidad CHECK (cantidad BETWEEN 1 AND 99)
);

CREATE INDEX ix_item_carrito_carrito ON item_carrito (fk_id_carrito);

-- ===========================================================================
-- 6. Identidad del panel
-- ===========================================================================

CREATE TABLE administrador (
    id_administrador bigint GENERATED BY DEFAULT AS IDENTITY,
    usuario          varchar(60)  NOT NULL,
    hash_contrasena  varchar(120) NOT NULL,
    nombre           varchar(120) NOT NULL,
    rol              varchar(20)  NOT NULL DEFAULT 'ADMINISTRADOR',
    activo           boolean      NOT NULL DEFAULT true,
    ultimo_acceso_en timestamptz,
    creado_en        timestamptz  NOT NULL DEFAULT now(),
    creado_por       varchar(60)  NOT NULL DEFAULT 'sistema',
    actualizado_en   timestamptz  NOT NULL DEFAULT now(),
    actualizado_por  varchar(60)  NOT NULL DEFAULT 'sistema',
    version          integer      NOT NULL DEFAULT 0,
    eliminado_en     timestamptz,
    eliminado_por    varchar(60),
    CONSTRAINT pk_administrador         PRIMARY KEY (id_administrador),
    -- El usuario NO se libera: queda escrito en creado_por y actualizado_por
    -- de todo lo que esa persona tocó.
    CONSTRAINT uq_administrador_usuario UNIQUE (usuario),
    CONSTRAINT ck_administrador_rol     CHECK (rol IN ('ADMINISTRADOR', 'SUPERADMINISTRADOR')),
    CONSTRAINT ck_administrador_eliminado CHECK ((eliminado_en IS NULL) = (eliminado_por IS NULL))
);

-- Token de refresco del panel.
--
-- Se guarda el HASH, nunca el token: quien lea esta tabla no puede fabricar
-- una sesión. Mismo razonamiento que con las contraseñas.
--
-- familia agrupa la cadena de rotaciones de un mismo acceso. Si un token ya
-- usado vuelve a presentarse, alguien lo copió: se revoca la familia entera,
-- no solo ese token.
CREATE TABLE token_refresco_admin (
    id_token_refresco_admin bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_administrador     bigint      NOT NULL,
    hash_token              varchar(64) NOT NULL,
    familia                 uuid        NOT NULL,
    expira_en               timestamptz NOT NULL,
    usado_en                timestamptz,
    revocado_en             timestamptz,
    creado_en               timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_token_refresco_admin      PRIMARY KEY (id_token_refresco_admin),
    CONSTRAINT uq_token_refresco_admin_hash UNIQUE (hash_token),
    CONSTRAINT fk_token_refresco_admin_administrador FOREIGN KEY (fk_id_administrador)
        REFERENCES administrador (id_administrador) ON DELETE CASCADE
);

CREATE INDEX ix_token_refresco_admin_familia ON token_refresco_admin (familia);
CREATE INDEX ix_token_refresco_admin_expira  ON token_refresco_admin (expira_en);

-- ===========================================================================
-- 7. Órdenes
-- ===========================================================================
--
-- Queda fuera de la eliminación lógica: una orden es un hecho ocurrido. No se
-- elimina, se cancela.

CREATE TABLE orden (
    id_orden        bigint GENERATED BY DEFAULT AS IDENTITY,
    -- Legible y no adivinable (RN-057): quien ve ORD-2026-A7K3M9 no puede
    -- deducir ORD-2026-A7K3M8 y consultar la orden de otra persona.
    numero          varchar(24)   NOT NULL,
    -- Una orden puede no tener cliente: se puede comprar sin cuenta. Por eso
    -- los datos de contacto se copian aquí y no se leen de `cliente`.
    fk_id_cliente   bigint,
    nombre_contacto varchar(120)  NOT NULL,
    email           varchar(160)  NOT NULL,
    telefono        varchar(20),
    direccion       varchar(300)  NOT NULL,
    subtotal        numeric(12,2) NOT NULL,
    descuento       numeric(12,2) NOT NULL DEFAULT 0,
    total           numeric(12,2) NOT NULL,
    -- Copiado, no referenciado: si el cupón se borra, la orden sigue diciendo
    -- con qué código se compró.
    codigo_cupon    varchar(40),
    estado          varchar(12)   NOT NULL DEFAULT 'PENDIENTE',
    creado_en       timestamptz   NOT NULL DEFAULT now(),
    creado_por      varchar(60)   NOT NULL DEFAULT 'sistema',
    actualizado_en  timestamptz   NOT NULL DEFAULT now(),
    actualizado_por varchar(60)   NOT NULL DEFAULT 'sistema',
    version         integer       NOT NULL DEFAULT 0,
    CONSTRAINT pk_orden           PRIMARY KEY (id_orden),
    CONSTRAINT uq_orden_numero    UNIQUE (numero),
    CONSTRAINT fk_orden_cliente   FOREIGN KEY (fk_id_cliente) REFERENCES cliente (id_cliente),
    CONSTRAINT ck_orden_estado    CHECK (estado IN ('PENDIENTE', 'PAGADA', 'ENVIADA', 'ENTREGADA', 'CANCELADA')),
    CONSTRAINT ck_orden_importes  CHECK (subtotal >= 0 AND descuento >= 0 AND total >= 0),
    CONSTRAINT ck_orden_descuento CHECK (descuento <= subtotal)
);

CREATE INDEX ix_orden_creado_en ON orden (creado_en DESC);
CREATE INDEX ix_orden_estado    ON orden (estado);
CREATE INDEX ix_orden_cliente   ON orden (fk_id_cliente);

-- El ítem de orden SÍ copia nombre, sku y precio. Es la contrapartida exacta
-- del ítem de carrito, que no copia nada: una orden es un hecho ocurrido, y si
-- mañana el producto sube de precio o se renombra, la orden del mes pasado
-- tiene que seguir diciendo lo que el cliente compró y pagó.
CREATE TABLE item_orden (
    id_item_orden   bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_orden     bigint        NOT NULL,
    -- Referencia solo para trazar. Los importes NO salen de aquí.
    fk_id_producto  bigint        NOT NULL,
    nombre_producto varchar(160)  NOT NULL,
    sku             varchar(40)   NOT NULL,
    precio_unitario numeric(12,2) NOT NULL,
    cantidad        integer       NOT NULL,
    total_linea     numeric(12,2) NOT NULL,
    CONSTRAINT pk_item_orden           PRIMARY KEY (id_item_orden),
    CONSTRAINT fk_item_orden_orden     FOREIGN KEY (fk_id_orden)    REFERENCES orden (id_orden) ON DELETE CASCADE,
    CONSTRAINT fk_item_orden_producto  FOREIGN KEY (fk_id_producto) REFERENCES producto (id_producto),
    CONSTRAINT uq_item_orden           UNIQUE (fk_id_orden, fk_id_producto),
    CONSTRAINT ck_item_orden_cantidad  CHECK (cantidad > 0),
    CONSTRAINT ck_item_orden_precio    CHECK (precio_unitario >= 0)
);

CREATE INDEX ix_item_orden_orden    ON item_orden (fk_id_orden);
CREATE INDEX ix_item_orden_producto ON item_orden (fk_id_producto);

-- ===========================================================================
-- 8. Chat de atención al cliente
-- ===========================================================================
--
-- Fuera de la eliminación lógica: una conversación no se elimina, se cierra.

CREATE TABLE conversacion (
    id_conversacion   bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_cliente     bigint       NOT NULL,
    -- Opcional: una conversación puede ser sobre una orden concreta o una
    -- consulta general.
    fk_id_orden       bigint,
    asunto            varchar(160) NOT NULL,
    estado            varchar(12)  NOT NULL DEFAULT 'ABIERTA',
    -- Quien tenga este UUID puede escribir como el cliente. Es el mismo
    -- mecanismo del carrito: identifica sin exigir cuenta, y no se adivina.
    token_acceso      uuid         NOT NULL DEFAULT gen_random_uuid(),
    ultimo_mensaje_en timestamptz,
    -- Desnormalizado a propósito: la bandeja ordena por actividad y muestra el
    -- contador sin contar mensajes de cada conversación en cada carga.
    no_leidos_admin   integer      NOT NULL DEFAULT 0,
    creado_en         timestamptz  NOT NULL DEFAULT now(),
    creado_por        varchar(60)  NOT NULL DEFAULT 'sistema',
    actualizado_en    timestamptz  NOT NULL DEFAULT now(),
    actualizado_por   varchar(60)  NOT NULL DEFAULT 'sistema',
    version           integer      NOT NULL DEFAULT 0,
    CONSTRAINT pk_conversacion          PRIMARY KEY (id_conversacion),
    CONSTRAINT uq_conversacion_token    UNIQUE (token_acceso),
    CONSTRAINT fk_conversacion_cliente  FOREIGN KEY (fk_id_cliente) REFERENCES cliente (id_cliente),
    CONSTRAINT fk_conversacion_orden    FOREIGN KEY (fk_id_orden)   REFERENCES orden (id_orden),
    CONSTRAINT ck_conversacion_estado   CHECK (estado IN ('ABIERTA', 'CERRADA')),
    CONSTRAINT ck_conversacion_noleidos CHECK (no_leidos_admin >= 0)
);

CREATE INDEX ix_conversacion_cliente   ON conversacion (fk_id_cliente);
CREATE INDEX ix_conversacion_actividad ON conversacion (ultimo_mensaje_en DESC NULLS LAST);
CREATE INDEX ix_conversacion_orden     ON conversacion (fk_id_orden) WHERE fk_id_orden IS NOT NULL;

CREATE TABLE mensaje (
    id_conversacion_mensaje bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_conversacion      bigint       NOT NULL,
    autor                   varchar(14)  NOT NULL,
    -- Copiado: si el administrador se elimina, el mensaje sigue diciendo quién
    -- respondió. Mismo criterio que las líneas de orden.
    autor_nombre            varchar(120) NOT NULL,
    cuerpo                  text,
    enviado_en              timestamptz  NOT NULL DEFAULT now(),
    leido_en                timestamptz,
    CONSTRAINT pk_mensaje              PRIMARY KEY (id_conversacion_mensaje),
    CONSTRAINT fk_mensaje_conversacion FOREIGN KEY (fk_id_conversacion)
        REFERENCES conversacion (id_conversacion) ON DELETE CASCADE,
    CONSTRAINT ck_mensaje_autor        CHECK (autor IN ('CLIENTE', 'ADMINISTRADOR'))
);

CREATE INDEX ix_mensaje_conversacion ON mensaje (fk_id_conversacion, enviado_en);

-- Adjuntos del chat. Tabla aparte de `archivo` porque aquí sí entra un PDF, y
-- `archivo` tiene un CHECK que solo admite WebP: mezclarlos obligaría a
-- relajar esa restricción y perder la garantía de que toda imagen del catálogo
-- está convertida.
CREATE TABLE adjunto (
    id_adjunto      bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_mensaje   bigint,
    clave           varchar(300) NOT NULL,
    nombre_original varchar(255) NOT NULL,
    tipo_mime       varchar(60)  NOT NULL,
    bytes           bigint       NOT NULL,
    url_publica     varchar(500) NOT NULL,
    creado_en       timestamptz  NOT NULL DEFAULT now(),
    creado_por      varchar(60)  NOT NULL DEFAULT 'sistema',
    CONSTRAINT pk_adjunto          PRIMARY KEY (id_adjunto),
    CONSTRAINT uq_adjunto_clave    UNIQUE (clave),
    CONSTRAINT fk_adjunto_mensaje  FOREIGN KEY (fk_id_mensaje)
        REFERENCES mensaje (id_conversacion_mensaje) ON DELETE CASCADE,
    -- Solo imagen convertida o PDF (RN-088). Cualquier otra cosa se rechaza
    -- antes de llegar aquí, y este CHECK es la última línea.
    CONSTRAINT ck_adjunto_tipo     CHECK (tipo_mime IN ('image/webp', 'application/pdf')),
    CONSTRAINT ck_adjunto_bytes    CHECK (bytes > 0)
);

CREATE INDEX ix_adjunto_mensaje ON adjunto (fk_id_mensaje);

-- ===========================================================================
-- 9. Notificaciones del panel
-- ===========================================================================
--
-- Son para todo el equipo, no por administrador: leerla la marca leída para
-- todos. Con un equipo pequeño es lo que se espera —lo que ya atendió alguien
-- no tiene que volver a aparecerle a otro—; el día que el equipo crezca se
-- añade una tabla de lecturas por administrador sin tocar quien las produce.
CREATE TABLE notificacion (
    id_notificacion bigint GENERATED BY DEFAULT AS IDENTITY,
    tipo            varchar(30)  NOT NULL,
    severidad       varchar(10)  NOT NULL DEFAULT 'INFO',
    titulo          varchar(160) NOT NULL,
    detalle         varchar(400),
    -- Ruta del panel a la que lleva. Guardada como texto porque la
    -- notificación no sabe de rutas: se la da quien la crea.
    enlace          varchar(200),
    -- Evita duplicar la misma alerta (RN-089): «producto 42 sin stock» es una
    -- sola notificación mientras siga sin leerse.
    clave_unicidad  varchar(120),
    leida_en        timestamptz,
    creado_en       timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT pk_notificacion       PRIMARY KEY (id_notificacion),
    CONSTRAINT ck_notificacion_sever CHECK (severidad IN ('INFO', 'AVISO', 'URGENTE')),
    CONSTRAINT ck_notificacion_tipo  CHECK (tipo IN (
        'STOCK_AGOTADO', 'STOCK_BAJO', 'ORDEN_NUEVA', 'ORDEN_CANCELADA', 'MENSAJE_CLIENTE'))
);

CREATE INDEX ix_notificacion_pendientes ON notificacion (creado_en DESC) WHERE leida_en IS NULL;
CREATE UNIQUE INDEX uq_notificacion_pendiente ON notificacion (clave_unicidad)
    WHERE leida_en IS NULL AND clave_unicidad IS NOT NULL;
