-- Esquema de catálogo.
--
-- Convención de nombres (ADR-0011):
--   tabla            español, singular            producto
--   clave primaria   id_<tabla>                   producto.id_producto
--   clave foránea    fk_id_<tabla_referenciada>   producto.fk_id_subcategoria
--   restricciones    pk_ uq_ fk_ ck_ ix_ + tabla
--
-- Bloque de auditoría, idéntico en toda tabla de negocio:
--   creado_en, creado_por, actualizado_en, actualizado_por, version

-- Búsqueda por nombre con ILIKE: sin trigramas es siempre un recorrido
-- completo de tabla. Ver ix_producto_busqueda al final.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ---------------------------------------------------------------------------
-- Archivos
-- ---------------------------------------------------------------------------

-- Un archivo es inmutable: no se edita, se reemplaza. Por eso no lleva
-- actualizado_por ni version: nada lo actualiza nunca.
CREATE TABLE archivo (
    id_archivo      bigint GENERATED BY DEFAULT AS IDENTITY,
    clave           varchar(300) NOT NULL,
    nombre_original varchar(255) NOT NULL,
    tipo_mime       varchar(60)  NOT NULL,
    bytes           bigint       NOT NULL,
    ancho           integer      NOT NULL,
    alto            integer      NOT NULL,
    texto_alt       varchar(200) NOT NULL,
    hash_contenido  varchar(64)  NOT NULL,
    url_publica     varchar(500) NOT NULL,
    creado_en       timestamptz  NOT NULL DEFAULT now(),
    creado_por      varchar(60)  NOT NULL DEFAULT 'sistema',
    CONSTRAINT pk_archivo           PRIMARY KEY (id_archivo),
    CONSTRAINT uq_archivo_clave     UNIQUE (clave),
    CONSTRAINT ck_archivo_tipo_mime CHECK (tipo_mime = 'image/webp'),
    CONSTRAINT ck_archivo_bytes     CHECK (bytes > 0),
    CONSTRAINT ck_archivo_dimension CHECK (ancho > 0 AND alto > 0)
);

-- La misma imagen en varios tamaños. El original acotado también es una
-- variante: así la consulta que arma una etiqueta picture es una sola.
CREATE TABLE archivo_variante (
    id_archivo_variante bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_archivo       bigint       NOT NULL,
    nombre              varchar(20)  NOT NULL,
    clave               varchar(300) NOT NULL,
    url_publica         varchar(500) NOT NULL,
    ancho               integer      NOT NULL,
    alto                integer      NOT NULL,
    bytes               bigint       NOT NULL,
    CONSTRAINT pk_archivo_variante         PRIMARY KEY (id_archivo_variante),
    CONSTRAINT fk_archivo_variante_archivo FOREIGN KEY (fk_id_archivo)
        REFERENCES archivo (id_archivo) ON DELETE CASCADE,
    CONSTRAINT uq_archivo_variante_nombre  UNIQUE (fk_id_archivo, nombre),
    CONSTRAINT ck_archivo_variante_nombre  CHECK (nombre IN ('MINIATURA', 'TARJETA', 'DETALLE', 'ORIGINAL'))
);

-- ---------------------------------------------------------------------------
-- Marca
-- ---------------------------------------------------------------------------

CREATE TABLE marca (
    id_marca        bigint GENERATED BY DEFAULT AS IDENTITY,
    nombre          varchar(80)  NOT NULL,
    slug            varchar(100) NOT NULL,
    descripcion     varchar(500),
    fk_id_archivo   bigint,
    activa          boolean      NOT NULL DEFAULT true,
    creado_en       timestamptz  NOT NULL DEFAULT now(),
    creado_por      varchar(60)  NOT NULL DEFAULT 'sistema',
    actualizado_en  timestamptz  NOT NULL DEFAULT now(),
    actualizado_por varchar(60)  NOT NULL DEFAULT 'sistema',
    version         integer      NOT NULL DEFAULT 0,
    CONSTRAINT pk_marca         PRIMARY KEY (id_marca),
    CONSTRAINT uq_marca_nombre  UNIQUE (nombre),
    CONSTRAINT uq_marca_slug    UNIQUE (slug),
    CONSTRAINT fk_marca_archivo FOREIGN KEY (fk_id_archivo) REFERENCES archivo (id_archivo)
);

-- ---------------------------------------------------------------------------
-- Categoría (nivel 1) y subcategoría (nivel 2)
-- ---------------------------------------------------------------------------

-- Una categoría NO contiene productos: solo subcategorías (modelo-dominio.md).
CREATE TABLE categoria (
    id_categoria    bigint GENERATED BY DEFAULT AS IDENTITY,
    nombre          varchar(80)  NOT NULL,
    slug            varchar(100) NOT NULL,
    descripcion     varchar(500),
    fk_id_archivo   bigint,
    orden           integer      NOT NULL DEFAULT 0,
    activa          boolean      NOT NULL DEFAULT true,
    creado_en       timestamptz  NOT NULL DEFAULT now(),
    creado_por      varchar(60)  NOT NULL DEFAULT 'sistema',
    actualizado_en  timestamptz  NOT NULL DEFAULT now(),
    actualizado_por varchar(60)  NOT NULL DEFAULT 'sistema',
    version         integer      NOT NULL DEFAULT 0,
    CONSTRAINT pk_categoria         PRIMARY KEY (id_categoria),
    CONSTRAINT uq_categoria_nombre  UNIQUE (nombre),
    CONSTRAINT uq_categoria_slug    UNIQUE (slug),
    CONSTRAINT fk_categoria_archivo FOREIGN KEY (fk_id_archivo) REFERENCES archivo (id_archivo)
);

-- El nombre es único DENTRO de la categoría (Accesorios existe bajo
-- Tecnología y bajo Deportes); el slug es único globalmente, para que
-- /c/accesorios-tecnologia no necesite saber el padre.
CREATE TABLE subcategoria (
    id_subcategoria  bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_categoria  bigint       NOT NULL,
    nombre           varchar(80)  NOT NULL,
    slug             varchar(120) NOT NULL,
    descripcion      varchar(500),
    fk_id_archivo    bigint,
    orden            integer      NOT NULL DEFAULT 0,
    activa           boolean      NOT NULL DEFAULT true,
    creado_en        timestamptz  NOT NULL DEFAULT now(),
    creado_por       varchar(60)  NOT NULL DEFAULT 'sistema',
    actualizado_en   timestamptz  NOT NULL DEFAULT now(),
    actualizado_por  varchar(60)  NOT NULL DEFAULT 'sistema',
    version          integer      NOT NULL DEFAULT 0,
    CONSTRAINT pk_subcategoria           PRIMARY KEY (id_subcategoria),
    CONSTRAINT uq_subcategoria_slug      UNIQUE (slug),
    CONSTRAINT uq_subcategoria_nombre    UNIQUE (fk_id_categoria, nombre),
    CONSTRAINT fk_subcategoria_categoria FOREIGN KEY (fk_id_categoria) REFERENCES categoria (id_categoria),
    CONSTRAINT fk_subcategoria_archivo   FOREIGN KEY (fk_id_archivo)   REFERENCES archivo (id_archivo)
);

CREATE INDEX ix_subcategoria_categoria ON subcategoria (fk_id_categoria, orden, nombre);

-- ---------------------------------------------------------------------------
-- Producto
-- ---------------------------------------------------------------------------

CREATE TABLE producto (
    id_producto           bigint GENERATED BY DEFAULT AS IDENTITY,
    sku                   varchar(40)   NOT NULL,
    nombre                varchar(160)  NOT NULL,
    slug                  varchar(200)  NOT NULL,
    descripcion_corta     varchar(300),
    descripcion           text,
    fk_id_subcategoria    bigint        NOT NULL,
    fk_id_marca           bigint,
    precio                numeric(12,2) NOT NULL,
    precio_anterior       numeric(12,2),
    stock                 integer       NOT NULL DEFAULT 0,
    destacado             boolean       NOT NULL DEFAULT false,
    activo                boolean       NOT NULL DEFAULT false,
    calificacion_promedio numeric(2,1)  NOT NULL DEFAULT 0,
    calificacion_conteo   integer       NOT NULL DEFAULT 0,
    creado_en             timestamptz   NOT NULL DEFAULT now(),
    creado_por            varchar(60)   NOT NULL DEFAULT 'sistema',
    actualizado_en        timestamptz   NOT NULL DEFAULT now(),
    actualizado_por       varchar(60)   NOT NULL DEFAULT 'sistema',
    version               integer       NOT NULL DEFAULT 0,
    CONSTRAINT pk_producto                 PRIMARY KEY (id_producto),
    CONSTRAINT uq_producto_sku             UNIQUE (sku),
    CONSTRAINT uq_producto_slug            UNIQUE (slug),
    CONSTRAINT fk_producto_subcategoria    FOREIGN KEY (fk_id_subcategoria) REFERENCES subcategoria (id_subcategoria),
    CONSTRAINT fk_producto_marca           FOREIGN KEY (fk_id_marca)        REFERENCES marca (id_marca),
    -- RN-003: el precio es estrictamente positivo. Un producto a cero no es
    -- gratis, es un error de captura.
    CONSTRAINT ck_producto_precio          CHECK (precio > 0),
    -- RN-004 / I-7: un descuento que sube el precio es un error de captura.
    CONSTRAINT ck_producto_precio_anterior CHECK (precio_anterior IS NULL OR precio_anterior > precio),
    CONSTRAINT ck_producto_stock           CHECK (stock >= 0),
    CONSTRAINT ck_producto_calificacion    CHECK (calificacion_promedio BETWEEN 0 AND 5)
);

CREATE INDEX ix_producto_subcategoria     ON producto (fk_id_subcategoria);
CREATE INDEX ix_producto_marca            ON producto (fk_id_marca);
CREATE INDEX ix_producto_activo_destacado ON producto (activo, destacado);
CREATE INDEX ix_producto_precio           ON producto (precio);
CREATE INDEX ix_producto_creado_en        ON producto (creado_en DESC);

-- RN-021: búsqueda por nombre y descripción corta. El trigrama es lo que
-- permite que un LIKE con comodín por delante use índice.
CREATE INDEX ix_producto_busqueda ON producto
    USING gin ((nombre || ' ' || coalesce(descripcion_corta, '')) gin_trgm_ops);

-- Orden explícito: la primera imagen es la principal. Sin UNIQUE sobre
-- (producto, orden) a propósito: reordenar exigiría restricciones diferidas
-- para no chocar a mitad del intercambio.
CREATE TABLE producto_imagen (
    id_producto_imagen bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_producto     bigint  NOT NULL,
    fk_id_archivo      bigint  NOT NULL,
    orden              integer NOT NULL DEFAULT 0,
    CONSTRAINT pk_producto_imagen          PRIMARY KEY (id_producto_imagen),
    CONSTRAINT fk_producto_imagen_producto FOREIGN KEY (fk_id_producto) REFERENCES producto (id_producto) ON DELETE CASCADE,
    CONSTRAINT fk_producto_imagen_archivo  FOREIGN KEY (fk_id_archivo)  REFERENCES archivo (id_archivo),
    CONSTRAINT uq_producto_imagen          UNIQUE (fk_id_producto, fk_id_archivo)
);

CREATE INDEX ix_producto_imagen_producto ON producto_imagen (fk_id_producto, orden);
