-- Carrito y cupones. Mismas convenciones que V001 (ADR-0011).

CREATE TABLE cupon (
    id_cupon        bigint GENERATED BY DEFAULT AS IDENTITY,
    codigo          varchar(40)   NOT NULL,
    tipo            varchar(12)   NOT NULL,
    valor           numeric(12,2) NOT NULL,
    subtotal_minimo numeric(12,2) NOT NULL DEFAULT 0,
    inicia_en       timestamptz   NOT NULL,
    termina_en      timestamptz   NOT NULL,
    usos_maximos    integer,
    usos_actuales   integer       NOT NULL DEFAULT 0,
    activo          boolean       NOT NULL DEFAULT true,
    creado_en       timestamptz   NOT NULL DEFAULT now(),
    creado_por      varchar(60)   NOT NULL DEFAULT 'sistema',
    actualizado_en  timestamptz   NOT NULL DEFAULT now(),
    actualizado_por varchar(60)   NOT NULL DEFAULT 'sistema',
    version         integer       NOT NULL DEFAULT 0,
    CONSTRAINT pk_cupon         PRIMARY KEY (id_cupon),
    CONSTRAINT uq_cupon_codigo  UNIQUE (codigo),
    CONSTRAINT ck_cupon_tipo    CHECK (tipo IN ('PORCENTAJE', 'MONTO_FIJO')),
    CONSTRAINT ck_cupon_valor   CHECK (valor > 0),
    -- Un porcentaje mayor a 100 regalaría dinero; el CHECK lo impide aunque
    -- el servicio falle.
    CONSTRAINT ck_cupon_porcentaje CHECK (tipo <> 'PORCENTAJE' OR valor <= 100),
    CONSTRAINT ck_cupon_periodo CHECK (termina_en > inicia_en),
    CONSTRAINT ck_cupon_usos    CHECK (usos_maximos IS NULL OR usos_actuales <= usos_maximos),
    CONSTRAINT ck_cupon_minimo  CHECK (subtotal_minimo >= 0)
);

-- El id es un UUID porque lo conoce el navegador: un entero secuencial
-- permitiría recorrer los carritos ajenos contando desde 1.
CREATE TABLE carrito (
    id_carrito      uuid         NOT NULL DEFAULT gen_random_uuid(),
    fk_id_cupon     bigint,
    estado          varchar(12)  NOT NULL DEFAULT 'ACTIVO',
    creado_en       timestamptz  NOT NULL DEFAULT now(),
    creado_por      varchar(60)  NOT NULL DEFAULT 'sistema',
    actualizado_en  timestamptz  NOT NULL DEFAULT now(),
    actualizado_por varchar(60)  NOT NULL DEFAULT 'sistema',
    version         integer      NOT NULL DEFAULT 0,
    CONSTRAINT pk_carrito        PRIMARY KEY (id_carrito),
    CONSTRAINT fk_carrito_cupon  FOREIGN KEY (fk_id_cupon) REFERENCES cupon (id_cupon),
    CONSTRAINT ck_carrito_estado CHECK (estado IN ('ACTIVO', 'CONVERTIDO'))
);

-- RN-031 / I-8: un producto ocupa una sola línea. Lo garantiza uq_item_carrito,
-- no el servicio: dos peticiones simultáneas ganan la carrera las dos.
CREATE TABLE item_carrito (
    id_item_carrito bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_carrito   uuid    NOT NULL,
    fk_id_producto  bigint  NOT NULL,
    cantidad        integer NOT NULL,
    CONSTRAINT pk_item_carrito          PRIMARY KEY (id_item_carrito),
    CONSTRAINT fk_item_carrito_carrito  FOREIGN KEY (fk_id_carrito)  REFERENCES carrito (id_carrito) ON DELETE CASCADE,
    CONSTRAINT fk_item_carrito_producto FOREIGN KEY (fk_id_producto) REFERENCES producto (id_producto),
    CONSTRAINT uq_item_carrito          UNIQUE (fk_id_carrito, fk_id_producto),
    -- RN-034: entre 1 y 99. Cero no es una cantidad, es un DELETE.
    CONSTRAINT ck_item_carrito_cantidad CHECK (cantidad BETWEEN 1 AND 99)
);

CREATE INDEX ix_item_carrito_carrito ON item_carrito (fk_id_carrito);
