-- Identidad del panel. Tabla separada de la de clientes a propósito
-- (ADR-0008): un fallo en el registro público no puede crear un administrador
-- porque no existe ningún camino que escriba en esta tabla desde fuera.

CREATE TABLE administrador (
    id_administrador bigint GENERATED BY DEFAULT AS IDENTITY,
    usuario          varchar(60)  NOT NULL,
    hash_contrasena  varchar(120) NOT NULL,
    nombre           varchar(120) NOT NULL,
    rol              varchar(20)  NOT NULL DEFAULT 'ADMINISTRADOR',
    activo           boolean      NOT NULL DEFAULT true,
    ultimo_acceso_en timestamptz,
    creado_en        timestamptz  NOT NULL DEFAULT now(),
    creado_por       varchar(60)  NOT NULL DEFAULT 'sistema',
    actualizado_en   timestamptz  NOT NULL DEFAULT now(),
    actualizado_por  varchar(60)  NOT NULL DEFAULT 'sistema',
    version          integer      NOT NULL DEFAULT 0,
    CONSTRAINT pk_administrador        PRIMARY KEY (id_administrador),
    CONSTRAINT uq_administrador_usuario UNIQUE (usuario),
    CONSTRAINT ck_administrador_rol    CHECK (rol IN ('ADMINISTRADOR', 'SUPERADMINISTRADOR'))
);

-- Token de refresco del panel.
--
-- Se guarda el HASH, nunca el token: quien lea esta tabla no puede fabricar
-- una sesión. Mismo razonamiento que con las contraseñas.
--
-- familia agrupa la cadena de rotaciones de un mismo acceso. Si un token ya
-- usado vuelve a presentarse, alguien lo copió: se revoca la familia entera,
-- no solo ese token.
CREATE TABLE token_refresco_admin (
    id_token_refresco_admin bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_administrador     bigint      NOT NULL,
    hash_token              varchar(64) NOT NULL,
    familia                 uuid        NOT NULL,
    expira_en               timestamptz NOT NULL,
    usado_en                timestamptz,
    revocado_en             timestamptz,
    creado_en               timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_token_refresco_admin      PRIMARY KEY (id_token_refresco_admin),
    CONSTRAINT uq_token_refresco_admin_hash UNIQUE (hash_token),
    CONSTRAINT fk_token_refresco_admin_administrador FOREIGN KEY (fk_id_administrador)
        REFERENCES administrador (id_administrador) ON DELETE CASCADE
);

CREATE INDEX ix_token_refresco_admin_familia ON token_refresco_admin (familia);
CREATE INDEX ix_token_refresco_admin_expira  ON token_refresco_admin (expira_en);
