-- Órdenes y métricas del panel.
--
-- Las órdenes se crean en el checkout, que todavía no existe. Las tablas sí,
-- porque el panel necesita listarlas y porque un tablero de ventas sin ventas
-- no es un tablero: es una maqueta. La semilla del final crea un histórico de
-- 90 días para que los gráficos muestren datos reales desde el primer arranque.

-- ---------------------------------------------------------------------------
-- Vistas de producto
-- ---------------------------------------------------------------------------

-- Contador simple, no una tabla de eventos. Para «qué producto se mira más»
-- basta, y una fila por visita a un catálogo público crece sin límite.
-- Si algún día hace falta la serie temporal, se añade la tabla y esta columna
-- se queda como acumulado.
ALTER TABLE producto ADD COLUMN vistas bigint NOT NULL DEFAULT 0;

CREATE INDEX ix_producto_vistas ON producto (vistas DESC);

-- ---------------------------------------------------------------------------
-- Orden
-- ---------------------------------------------------------------------------

CREATE TABLE orden (
    id_orden        bigint GENERATED BY DEFAULT AS IDENTITY,
    -- Legible y no adivinable (RN-057): quien ve ORD-2026-A7K3M9 no puede
    -- deducir ORD-2026-A7K3M8 y consultar la orden de otra persona.
    numero          varchar(24)   NOT NULL,
    nombre_contacto varchar(120)  NOT NULL,
    email           varchar(160)  NOT NULL,
    telefono        varchar(20),
    direccion       varchar(300)  NOT NULL,
    subtotal        numeric(12,2) NOT NULL,
    descuento       numeric(12,2) NOT NULL DEFAULT 0,
    total           numeric(12,2) NOT NULL,
    -- Copiado, no referenciado: si el cupón se borra, la orden sigue diciendo
    -- con qué código se compró.
    codigo_cupon    varchar(40),
    estado          varchar(12)   NOT NULL DEFAULT 'PENDIENTE',
    creado_en       timestamptz   NOT NULL DEFAULT now(),
    creado_por      varchar(60)   NOT NULL DEFAULT 'sistema',
    actualizado_en  timestamptz   NOT NULL DEFAULT now(),
    actualizado_por varchar(60)   NOT NULL DEFAULT 'sistema',
    version         integer       NOT NULL DEFAULT 0,
    CONSTRAINT pk_orden           PRIMARY KEY (id_orden),
    CONSTRAINT uq_orden_numero    UNIQUE (numero),
    CONSTRAINT ck_orden_estado    CHECK (estado IN ('PENDIENTE', 'PAGADA', 'ENVIADA', 'ENTREGADA', 'CANCELADA')),
    CONSTRAINT ck_orden_importes  CHECK (subtotal >= 0 AND descuento >= 0 AND total >= 0),
    CONSTRAINT ck_orden_descuento CHECK (descuento <= subtotal)
);

CREATE INDEX ix_orden_creado_en ON orden (creado_en DESC);
CREATE INDEX ix_orden_estado    ON orden (estado);

-- El ítem de orden SÍ copia nombre, sku y precio. Es la contrapartida exacta
-- del ítem de carrito, que no copia nada: una orden es un hecho ocurrido, y si
-- mañana el producto sube de precio o se renombra, la orden del mes pasado
-- tiene que seguir diciendo lo que el cliente compró y pagó.
CREATE TABLE item_orden (
    id_item_orden   bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_orden     bigint        NOT NULL,
    -- Referencia solo para trazar. Los importes NO salen de aquí.
    fk_id_producto  bigint        NOT NULL,
    nombre_producto varchar(160)  NOT NULL,
    sku             varchar(40)   NOT NULL,
    precio_unitario numeric(12,2) NOT NULL,
    cantidad        integer       NOT NULL,
    total_linea     numeric(12,2) NOT NULL,
    CONSTRAINT pk_item_orden           PRIMARY KEY (id_item_orden),
    CONSTRAINT fk_item_orden_orden     FOREIGN KEY (fk_id_orden)    REFERENCES orden (id_orden) ON DELETE CASCADE,
    CONSTRAINT fk_item_orden_producto  FOREIGN KEY (fk_id_producto) REFERENCES producto (id_producto),
    CONSTRAINT uq_item_orden           UNIQUE (fk_id_orden, fk_id_producto),
    CONSTRAINT ck_item_orden_cantidad  CHECK (cantidad > 0),
    CONSTRAINT ck_item_orden_precio    CHECK (precio_unitario >= 0)
);

CREATE INDEX ix_item_orden_orden    ON item_orden (fk_id_orden);
CREATE INDEX ix_item_orden_producto ON item_orden (fk_id_producto);

-- ---------------------------------------------------------------------------
-- Histórico de demostración
-- ---------------------------------------------------------------------------
--
-- Todo es determinista: las mismas migraciones producen los mismos datos. Un
-- seed con random() da un tablero distinto en cada máquina y hace imposible
-- decir «aquí debería salir 12».

-- Vistas: entre 40 y 940, repartidas de forma estable por producto.
UPDATE producto SET vistas = 40 + (id_producto * 137) % 900;

WITH dias AS (
    SELECT d AS dia, (now()::date - d)::timestamptz + interval '9 hours' AS apertura
    FROM generate_series(0, 89) AS d
),
pedidos AS (
    SELECT dias.dia,
           n,
           dias.apertura + (n * interval '3 hours') AS creada,
           (dias.dia * 7 + n * 13) AS semilla
    FROM dias
    CROSS JOIN generate_series(1, 3) AS n
    -- Deja fuera un 40% de las combinaciones: algunos días tienen tres
    -- órdenes, otros una y otros ninguna. Un histórico plano no se parece a
    -- ninguna tienda.
    WHERE (dias.dia * 7 + n * 13) % 5 < 3
)
INSERT INTO orden (numero, nombre_contacto, email, telefono, direccion,
                   subtotal, descuento, total, estado, creado_en, actualizado_en)
SELECT
    'ORD-' || to_char(p.creada, 'YYYY') || '-' || upper(substr(md5(p.dia::text || '-' || p.n::text), 1, 6)),
    c.nombre,
    lower(translate(split_part(c.nombre, ' ', 1), 'áéíóúÁÉÍÓÚñÑ', 'aeiouAEIOUnN'))
        || (p.semilla % 97) || '@example.com',
    '9' || lpad(((p.semilla * 137) % 100000000)::text, 8, '0'),
    c.direccion,
    0, 0, 0,
    CASE
        WHEN p.dia <= 2            THEN 'PENDIENTE'
        WHEN p.semilla % 13 = 0    THEN 'CANCELADA'
        WHEN p.dia <= 5            THEN 'PAGADA'
        WHEN p.dia <= 12           THEN 'ENVIADA'
        ELSE 'ENTREGADA'
    END,
    p.creada,
    p.creada
FROM pedidos p
JOIN LATERAL (
    SELECT nombre, direccion
    FROM (VALUES
        ('María Quispe',     'Av. Arequipa 1234, Lince, Lima'),
        ('Carlos Mendoza',   'Jr. Puno 456, Cercado, Arequipa'),
        ('Lucía Fernández',  'Calle Los Pinos 78, Trujillo'),
        ('Jorge Ramírez',    'Av. El Sol 990, Cusco'),
        ('Ana Torres',       'Av. Grau 321, Miraflores, Lima'),
        ('Diego Salazar',    'Jr. Junín 55, Huancayo'),
        ('Valeria Chávez',   'Av. La Marina 2100, San Miguel, Lima'),
        ('Renzo Paredes',    'Calle Bolognesi 14, Piura')
    ) AS v(nombre, direccion)
    OFFSET (p.semilla % 8) LIMIT 1
) c ON true;

-- Líneas: entre 1 y 3 productos por orden, sin repetir producto en la misma.
WITH catalogo AS (
    SELECT p.id_producto, p.nombre, p.sku, p.precio,
           row_number() OVER (ORDER BY p.id_producto) - 1 AS posicion,
           count(*) OVER () AS cuantos
    FROM producto p
    WHERE p.activo
)
INSERT INTO item_orden (fk_id_orden, fk_id_producto, nombre_producto, sku, precio_unitario, cantidad, total_linea)
SELECT DISTINCT ON (o.id_orden, c.id_producto)
    o.id_orden,
    c.id_producto,
    c.nombre,
    c.sku,
    c.precio,
    1 + ((o.id_orden + k) % 3),
    c.precio * (1 + ((o.id_orden + k) % 3))
FROM orden o
CROSS JOIN generate_series(0, 2) AS k
JOIN catalogo c ON c.posicion = ((o.id_orden * 17 + k * 31) % c.cuantos)
WHERE k <= (o.id_orden % 3);

-- Los importes se calculan desde las líneas, nunca al revés: si alguna vez no
-- cuadran, el defecto está en quien escribió la orden, no en el tablero.
UPDATE orden o
SET subtotal = suma.importe,
    descuento = CASE WHEN o.id_orden % 5 = 0 THEN round(suma.importe * 0.10, 2) ELSE 0 END,
    codigo_cupon = CASE WHEN o.id_orden % 5 = 0 THEN 'BIENVENIDA10' ELSE NULL END,
    total = suma.importe - CASE WHEN o.id_orden % 5 = 0 THEN round(suma.importe * 0.10, 2) ELSE 0 END
FROM (SELECT fk_id_orden, sum(total_linea) AS importe FROM item_orden GROUP BY fk_id_orden) suma
WHERE suma.fk_id_orden = o.id_orden;

-- Una orden sin líneas no tiene sentido; si la aleatoriedad dejó alguna, fuera.
DELETE FROM orden WHERE id_orden NOT IN (SELECT fk_id_orden FROM item_orden);
