-- Clientes.
--
-- Tabla separada de la de administradores (ADR-0008). Con una sola tabla y un
-- campo `rol`, cualquier fallo del registro público sería una escalada a
-- administrador; aquí ese camino no existe.
--
-- El registro y el acceso con Google llegan con el bloque de identidad. Lo que
-- hay ahora es lo que el panel necesita: saber quién compró y poder hablar con
-- esa persona.

CREATE TABLE cliente (
    id_cliente       bigint GENERATED BY DEFAULT AS IDENTITY,
    email            varchar(160) NOT NULL,
    email_verificado boolean      NOT NULL DEFAULT false,
    -- Nulo es un estado legítimo: quien entró con Google no tiene contraseña,
    -- y pedirle «la actual» para cambiarla no tendría sentido.
    hash_contrasena  varchar(120),
    nombre           varchar(120) NOT NULL,
    telefono         varchar(20),
    activo           boolean      NOT NULL DEFAULT true,
    ultimo_acceso_en timestamptz,
    creado_en        timestamptz  NOT NULL DEFAULT now(),
    creado_por       varchar(60)  NOT NULL DEFAULT 'sistema',
    actualizado_en   timestamptz  NOT NULL DEFAULT now(),
    actualizado_por  varchar(60)  NOT NULL DEFAULT 'sistema',
    version          integer      NOT NULL DEFAULT 0,
    eliminado_en     timestamptz,
    eliminado_por    varchar(60),
    CONSTRAINT pk_cliente           PRIMARY KEY (id_cliente),
    CONSTRAINT ck_cliente_eliminado CHECK ((eliminado_en IS NULL) = (eliminado_por IS NULL)),
    -- El correo en minúsculas es la identidad. Se comprueba con lower() para
    -- que Ana@x.com y ana@x.com no sean dos cuentas distintas.
    CONSTRAINT ck_cliente_email     CHECK (email = lower(email))
);

CREATE UNIQUE INDEX uq_cliente_email ON cliente (email) WHERE eliminado_en IS NULL;
CREATE INDEX ix_cliente_nombre ON cliente (nombre);

-- Una orden puede no tener cliente: se puede comprar sin cuenta. Por eso los
-- datos de contacto se copian en la orden y no se leen de aquí.
ALTER TABLE orden ADD COLUMN fk_id_cliente bigint;
ALTER TABLE orden ADD CONSTRAINT fk_orden_cliente FOREIGN KEY (fk_id_cliente) REFERENCES cliente (id_cliente);
CREATE INDEX ix_orden_cliente ON orden (fk_id_cliente);

-- El enlace que hará falta para fusionar el carrito anónimo al iniciar sesión
-- (RN-036). La fusión en sí llega con el bloque de identidad.
ALTER TABLE carrito ADD COLUMN fk_id_cliente bigint;
ALTER TABLE carrito ADD CONSTRAINT fk_carrito_cliente FOREIGN KEY (fk_id_cliente) REFERENCES cliente (id_cliente);

-- ---------------------------------------------------------------------------
-- Clientes de demostración, a partir de quienes ya compraron
-- ---------------------------------------------------------------------------

INSERT INTO cliente (email, email_verificado, nombre, telefono, creado_en)
SELECT
    lower(translate(replace(v.nombre, ' ', '.'), 'áéíóúÁÉÍÓÚñÑ', 'aeiouAEIOUnN')) || '@example.com',
    v.verificado,
    v.nombre,
    v.telefono,
    now() - make_interval(days => v.dias_atras)
FROM (VALUES
    ('María Quispe',    true,  '987654321', 120),
    ('Carlos Mendoza',  true,  '987112233', 110),
    ('Lucía Fernández', true,  '986554433', 100),
    ('Jorge Ramírez',   false, '985443322',  95),
    ('Ana Torres',      true,  '984332211',  80),
    ('Diego Salazar',   true,  '983221100',  60),
    ('Valeria Chávez',  false, '982110099',  40),
    ('Renzo Paredes',   true,  '981009988',  25)
) AS v(nombre, verificado, telefono, dias_atras);

-- Las órdenes sembradas por V005 usaban estos mismos nombres: se enlazan y se
-- normaliza el correo para que el de la orden y el de la cuenta coincidan.
UPDATE orden o
SET fk_id_cliente = c.id_cliente,
    email = c.email,
    telefono = c.telefono
FROM cliente c
WHERE c.nombre = o.nombre_contacto;
