-- Chat de atención al cliente y notificaciones del panel.

-- ---------------------------------------------------------------------------
-- Conversación
-- ---------------------------------------------------------------------------

CREATE TABLE conversacion (
    id_conversacion   bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_cliente     bigint       NOT NULL,
    -- Opcional: una conversación puede ser sobre una orden concreta o una
    -- consulta general.
    fk_id_orden       bigint,
    asunto            varchar(160) NOT NULL,
    estado            varchar(12)  NOT NULL DEFAULT 'ABIERTA',
    -- Quien tenga este UUID puede escribir como el cliente. Es el mismo
    -- mecanismo del carrito: identifica sin exigir cuenta, y no se adivina.
    token_acceso      uuid         NOT NULL DEFAULT gen_random_uuid(),
    ultimo_mensaje_en timestamptz,
    -- Desnormalizado a propósito: la bandeja ordena por actividad y muestra el
    -- contador sin contar mensajes de cada conversación en cada carga.
    no_leidos_admin   integer      NOT NULL DEFAULT 0,
    creado_en         timestamptz  NOT NULL DEFAULT now(),
    creado_por        varchar(60)  NOT NULL DEFAULT 'sistema',
    actualizado_en    timestamptz  NOT NULL DEFAULT now(),
    actualizado_por   varchar(60)  NOT NULL DEFAULT 'sistema',
    version           integer      NOT NULL DEFAULT 0,
    CONSTRAINT pk_conversacion          PRIMARY KEY (id_conversacion),
    CONSTRAINT uq_conversacion_token    UNIQUE (token_acceso),
    CONSTRAINT fk_conversacion_cliente  FOREIGN KEY (fk_id_cliente) REFERENCES cliente (id_cliente),
    CONSTRAINT fk_conversacion_orden    FOREIGN KEY (fk_id_orden)   REFERENCES orden (id_orden),
    CONSTRAINT ck_conversacion_estado   CHECK (estado IN ('ABIERTA', 'CERRADA')),
    CONSTRAINT ck_conversacion_noleidos CHECK (no_leidos_admin >= 0)
);

CREATE INDEX ix_conversacion_cliente  ON conversacion (fk_id_cliente);
CREATE INDEX ix_conversacion_actividad ON conversacion (ultimo_mensaje_en DESC NULLS LAST);

CREATE TABLE mensaje (
    id_conversacion_mensaje bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_conversacion      bigint       NOT NULL,
    autor                   varchar(14)  NOT NULL,
    -- Copiado: si el administrador se elimina, el mensaje sigue diciendo quién
    -- respondió. Mismo criterio que las líneas de orden.
    autor_nombre            varchar(120) NOT NULL,
    cuerpo                  text,
    enviado_en              timestamptz  NOT NULL DEFAULT now(),
    leido_en                timestamptz,
    CONSTRAINT pk_mensaje              PRIMARY KEY (id_conversacion_mensaje),
    CONSTRAINT fk_mensaje_conversacion FOREIGN KEY (fk_id_conversacion)
        REFERENCES conversacion (id_conversacion) ON DELETE CASCADE,
    CONSTRAINT ck_mensaje_autor        CHECK (autor IN ('CLIENTE', 'ADMINISTRADOR'))
);

CREATE INDEX ix_mensaje_conversacion ON mensaje (fk_id_conversacion, enviado_en);

-- Adjuntos del chat. Tabla aparte de `archivo` porque aquí sí entra un PDF, y
-- `archivo` tiene un CHECK que solo admite WebP: mezclarlos obligaría a
-- relajar esa restricción y perder la garantía de que toda imagen del catálogo
-- está convertida.
CREATE TABLE adjunto (
    id_adjunto      bigint GENERATED BY DEFAULT AS IDENTITY,
    fk_id_mensaje   bigint,
    clave           varchar(300) NOT NULL,
    nombre_original varchar(255) NOT NULL,
    tipo_mime       varchar(60)  NOT NULL,
    bytes           bigint       NOT NULL,
    url_publica     varchar(500) NOT NULL,
    creado_en       timestamptz  NOT NULL DEFAULT now(),
    creado_por      varchar(60)  NOT NULL DEFAULT 'sistema',
    CONSTRAINT pk_adjunto          PRIMARY KEY (id_adjunto),
    CONSTRAINT uq_adjunto_clave    UNIQUE (clave),
    CONSTRAINT fk_adjunto_mensaje  FOREIGN KEY (fk_id_mensaje)
        REFERENCES mensaje (id_conversacion_mensaje) ON DELETE CASCADE,
    -- Solo imagen convertida o PDF. Cualquier otra cosa se rechaza antes de
    -- llegar aquí, y este CHECK es la última línea.
    CONSTRAINT ck_adjunto_tipo     CHECK (tipo_mime IN ('image/webp', 'application/pdf')),
    CONSTRAINT ck_adjunto_bytes    CHECK (bytes > 0)
);

CREATE INDEX ix_adjunto_mensaje ON adjunto (fk_id_mensaje);

-- ---------------------------------------------------------------------------
-- Notificaciones del panel
-- ---------------------------------------------------------------------------
--
-- Son para todo el equipo, no por administrador: leerla la marca leída para
-- todos. Con un equipo pequeño es lo que se espera —lo que ya atendió alguien
-- no tiene que volver a aparecerle a otro—; el día que el equipo crezca se
-- añade una tabla de lecturas por administrador sin tocar quien las produce.
CREATE TABLE notificacion (
    id_notificacion bigint GENERATED BY DEFAULT AS IDENTITY,
    tipo            varchar(30)  NOT NULL,
    severidad       varchar(10)  NOT NULL DEFAULT 'INFO',
    titulo          varchar(160) NOT NULL,
    detalle         varchar(400),
    -- Ruta del panel a la que lleva. Guardada como texto porque la
    -- notificación no sabe de rutas: se la da quien la crea.
    enlace          varchar(200),
    -- Evita duplicar la misma alerta: «producto 42 sin stock» es una sola
    -- notificación mientras siga sin leerse.
    clave_unicidad  varchar(120),
    leida_en        timestamptz,
    creado_en       timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT pk_notificacion        PRIMARY KEY (id_notificacion),
    CONSTRAINT ck_notificacion_sever  CHECK (severidad IN ('INFO', 'AVISO', 'URGENTE')),
    CONSTRAINT ck_notificacion_tipo   CHECK (tipo IN (
        'STOCK_AGOTADO', 'STOCK_BAJO', 'ORDEN_NUEVA', 'ORDEN_CANCELADA', 'MENSAJE_CLIENTE'))
);

CREATE INDEX ix_notificacion_pendientes ON notificacion (creado_en DESC) WHERE leida_en IS NULL;
CREATE UNIQUE INDEX uq_notificacion_pendiente ON notificacion (clave_unicidad)
    WHERE leida_en IS NULL AND clave_unicidad IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Conversaciones de demostración
-- ---------------------------------------------------------------------------

INSERT INTO conversacion (fk_id_cliente, fk_id_orden, asunto, ultimo_mensaje_en, no_leidos_admin, creado_en)
SELECT c.id_cliente,
       o.id_orden,
       v.asunto,
       now() - make_interval(hours => v.horas_atras),
       v.no_leidos,
       now() - make_interval(hours => v.horas_atras + 2)
FROM (VALUES
    ('María Quispe',    '¿Cuándo llega mi pedido?',        3, 1),
    ('Carlos Mendoza',  'Consulta sobre la garantía',     28, 0),
    ('Valeria Chávez',  'Quiero cambiar la dirección',     9, 2)
) AS v(nombre, asunto, horas_atras, no_leidos)
JOIN cliente c ON c.nombre = v.nombre
LEFT JOIN LATERAL (
    SELECT id_orden FROM orden WHERE fk_id_cliente = c.id_cliente ORDER BY creado_en DESC LIMIT 1
) o ON true;

INSERT INTO mensaje (fk_id_conversacion, autor, autor_nombre, cuerpo, enviado_en, leido_en)
SELECT conv.id_conversacion,
       v.autor,
       CASE WHEN v.autor = 'CLIENTE' THEN cli.nombre ELSE 'Administrador General' END,
       v.cuerpo,
       conv.creado_en + make_interval(mins => v.minutos),
       CASE WHEN v.leido THEN conv.creado_en + make_interval(mins => v.minutos + 5) ELSE NULL END
FROM conversacion conv
JOIN cliente cli ON cli.id_cliente = conv.fk_id_cliente
JOIN LATERAL (
    VALUES
        ('CLIENTE',       'Hola, buenas tardes. Quería consultar por mi compra.', 0,  true),
        ('ADMINISTRADOR', 'Hola, con gusto te ayudo. Déjame revisar tu orden.',   12, true),
        ('CLIENTE',       'Gracias, quedo atento.',                               35, false)
) AS v(autor, cuerpo, minutos, leido) ON true;

UPDATE conversacion c
SET ultimo_mensaje_en = m.ultimo
FROM (SELECT fk_id_conversacion, max(enviado_en) AS ultimo FROM mensaje GROUP BY fk_id_conversacion) m
WHERE m.fk_id_conversacion = c.id_conversacion;

-- Una notificación por cada conversación con mensajes sin leer, para que la
-- campana del panel tenga algo que mostrar desde el primer arranque.
INSERT INTO notificacion (tipo, severidad, titulo, detalle, enlace, clave_unicidad, creado_en)
SELECT 'MENSAJE_CLIENTE',
       'AVISO',
       'Mensaje de ' || cli.nombre,
       c.asunto,
       '/conversaciones?abrir=' || c.id_conversacion,
       'conversacion:' || c.id_conversacion,
       c.ultimo_mensaje_en
FROM conversacion c
JOIN cliente cli ON cli.id_cliente = c.fk_id_cliente
WHERE c.no_leidos_admin > 0;

INSERT INTO notificacion (tipo, severidad, titulo, detalle, enlace, clave_unicidad, creado_en)
SELECT 'STOCK_AGOTADO',
       'URGENTE',
       'Sin stock: ' || p.nombre,
       'El producto sigue publicado y no se puede comprar.',
       '/productos/' || p.id_producto,
       'stock-agotado:' || p.id_producto,
       now() - interval '4 hours'
FROM producto p
WHERE p.activo = true AND p.stock = 0 AND p.eliminado_en IS NULL;
